version: "3.2"

services:
 influxdb:
   image: influxdb
   container_name: influxdb
   volumes:
    - ./influxdb/data:/var/lib/influxdb
    - ./influxdb/config/:/etc/influxdb/
   ports:
   - "8082:8082"
   - "8086:8086"
   - "8089:8089"
   restart: always

 telegraf:
   image: telegraf
   container_name: telegraf
   volumes: 
   - ./telegraf/:/etc/telegraf/
   - /run/docker.sock:/var/run/docker.sock
   - /sys:/rootfs/sys:ro
   - /proc:/rootfs/proc:ro
   - /etc:/rootfs/etc:ro
   environment:
   - HOST_PROC=/host/proc
   network_mode: "host"
   restart: always

 grafana:
   image: proxx/grafana-armv7
   container_name: grafana
   ports:
   - "3000:3000"
   volumes:
   - ./grafana:/var/lib/grafana
   user: "0"
   links: 
   - influxdb
   restart: always
