version: "3.2"

services:
 influxdb:
   image: influxdb
   container_name: influxdb
   volumes:
    - ./influxdb/data:/var/lib/influxdb
    - ./influxdb/config/:/etc/influxdb/
    - /run/docker.sock:/var/run/docker.sock 
   ports:
   - "8082:8082"
   - "8086:8086"
   - "8089:8089"
   restart: always

 telegraf:
   image: telegraf
   container_name: telegraf
   volumes: 
   - ./telegraf/:/etc/telegraf/
   - /:/hostfs:ro
   environment:
   - HOST_PROC=/hostfs/proc
   - HOST_ETC=/hostfs/etc
   - HOST_SYS=/hostfs/sys
   - HOST_VAR=/hostfs/var
   - HOST_MOUNT_PREFIX=/hostfs
   - HOST_RUN=/hostfs/run
   network_mode: "host"
   restart: always

 grafana:
   image: proxx/grafana-armv7
   container_name: grafana
   ports:
   - "3000:3000"
   volumes:
   - ./grafana:/var/lib/grafana
   user: "0"
   links: 
   - influxdb
   restart: always
