# TIG stack on hypriot (Raspbi 3)

version: "3"

services:
 influxdb:
   image: hypriot/rpi-influxdb:latest
   volumes:
    - /home/pirate/tig-docker/influxdb/data:/var/lib/influxdb
    - /home/pirate/tig-docker/influxdb/config/:/etc/influxdb/
   ports:
   - "8082:8082"
   - "8086:8086"
   - "8089:8089"
   restart: unless-stopped

 telegraf:
   image: arm32v7/telegraf:latest
   volumes: 
   - /home/pirate/tig-docker/telegraf/:/etc/telegraf/
   - /run/docker.sock:/var/run/docker.sock
   - /proc:/host/proc:ro
   environment:
   - HOST_PROC=/host/proc
   network_mode: "host"
   restart: unless-stopped

 grafana:
   image: fg2it/grafana-armhf:v5.1.4
   ports:
   - "3000:3000"
   links: 
   - influxdb
   restart: unless-stopped